"""Configuration module for Market Mayhem backend."""

from .llm_config import (
    GEMINI_MODEL,
    TEMPERATURE_EVENT_GENERATOR,
    TEMPERATURE_PORTFOLIO,
    TEMPERATURE_NEWS,
    TEMPERATURE_PRICE,
    TEMPERATURE_VILLAIN,
    TEMPERATURE_INSIGHT,
    TEMPERATURE_SUPERVISOR
)

__all__ = [
    "GEMINI_MODEL",
    "TEMPERATURE_EVENT_GENERATOR",
    "TEMPERATURE_PORTFOLIO",
    "TEMPERATURE_NEWS",
    "TEMPERATURE_PRICE",
    "TEMPERATURE_VILLAIN",
    "TEMPERATURE_INSIGHT",
    "TEMPERATURE_SUPERVISOR"
]
